version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "feedback4u_db"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./feedback
      dockerfile: Dockerfile
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - auth-backend

volumes:
  auth_pgdata:
  rag_pgdata:
