services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag-postgres
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../backend/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro   # ← add
volumes:
  pgdata:
